;AVIFILDLL = 'AVIFIL32.DLL'

import avifil32,\
  AVIBuildFilterA,'AVIBuildFilterA',\ ;-
  AVIBuildFilterW,'AVIBuildFilterW',\ ;-
  AVIClearClipboard,'AVIClearClipboard',\ ;-
  AVIFileAddRef,'AVIFileAddRef',\ ;-
  AVIFileCreateStreamA,'AVIFileCreateStreamA',\
  AVIFileCreateStreamW,'AVIFileCreateStreamW',\ ;-
  AVIFileEndRecord,'AVIFileEndRecord',\ ;-       
  AVIFileExit,'AVIFileExit',\
  AVIFileGetStream,'AVIFileGetStream',\
  AVIFileInfoA,'AVIFileInfoA',\ ;-
  AVIFileInfoW,'AVIFileInfoW',\ ;-
  AVIFileInit,'AVIFileInit',\
  AVIFileOpenA,'AVIFileOpenA',\
  AVIFileOpenW,'AVIFileOpenW',\ ;-
  AVIFileReadData,'AVIFileReadData',\
  AVIFileRelease,'AVIFileRelease',\
  AVIFileWriteData,'AVIFileWriteData',\ ;-
  AVIGetFromClipboard,'AVIGetFromClipboard',\ ;-
  AVIMakeCompressedStream,'AVIMakeCompressedStream',\ ;-
  AVIMakeFileFromStreams,'AVIMakeFileFromStreams',\
  AVIMakeStreamFromClipboard,'AVIMakeStreamFromClipboard',\ ;-
  AVIPutFileOnClipboard,'AVIPutFileOnClipboard',\ ;-
  AVISaveA,'AVISaveA',\ ;-
  AVISaveOptions,'AVISaveOptions',\ ;-
  AVISaveOptionsFree,'AVISaveOptionsFree',\ ;-
  AVISaveVA,'AVISaveVA',\ ;-
  AVISaveVW,'AVISaveVW',\ ;-
  AVISaveW,'AVISaveW',\ ;-
  AVIStreamAddRef,'AVIStreamAddRef',\ ;-
  AVIStreamBeginStreaming,'AVIStreamBeginStreaming',\
  AVIStreamCreate,'AVIStreamCreate',\ ;-
  AVIStreamEndStreaming,'AVIStreamEndStreaming',\
  AVIStreamFindSample,'AVIStreamFindSample',\ ;-
  AVIStreamGetFrame,'AVIStreamGetFrame',\
  AVIStreamGetFrameClose,'AVIStreamGetFrameClose',\
  AVIStreamGetFrameOpen,'AVIStreamGetFrameOpen',\
  AVIStreamInfoA,'AVIStreamInfoA',\ ;-
  AVIStreamInfoW,'AVIStreamInfoW',\ ;-
  AVIStreamLength,'AVIStreamLength',\
  AVIStreamOpenFromFileA,'AVIStreamOpenFromFileA',\ ;-
  AVIStreamOpenFromFileW,'AVIStreamOpenFromFileW',\ ;-
  AVIStreamRead,'AVIStreamRead',\ ;-
  AVIStreamReadData,'AVIStreamReadData',\ ;-
  AVIStreamReadFormat,'AVIStreamReadFormat',\
  AVIStreamRelease,'AVIStreamRelease',\
  AVIStreamSampleToTime,'AVIStreamSampleToTime',\ ;-
  AVIStreamSetFormat,'AVIStreamSetFormat',\
  AVIStreamStart,'AVIStreamStart',\ ;-
  AVIStreamTimeToSample,'AVIStreamTimeToSample',\ ;-
  AVIStreamWrite,'AVIStreamWrite',\
  AVIStreamWriteData,'AVIStreamWriteData',\
  CreateEditableStream,'CreateEditableStream',\
  DllCanUnloadNow,'DllCanUnloadNow',\ ;-
  DllGetClassObject,'DllGetClassObject',\ ;-
  EditStreamClone,'EditStreamClone',\ ;-
  EditStreamCopy,'EditStreamCopy',\ ;-
  EditStreamCut,'EditStreamCut',\ ;-
  EditStreamPaste,'EditStreamPaste',\ ;-
  EditStreamSetInfoA,'EditStreamSetInfoA',\ ;-
  EditStreamSetInfoW,'EditStreamSetInfoW',\ ;-
  EditStreamSetNameA,'EditStreamSetNameA',\ ;-
  EditStreamSetNameW,'EditStreamSetNameW',\ ;-
  IID_IAVIEditStream,'IID_IAVIEditStream',\ ;-
  IID_IAVIFile,'IID_IAVIFile',\ ;-
  IID_IAVIStream,'IID_IAVIStream',\ ;-
  IID_IGetFrame,'IID_IGetFrame'